apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mtc7mndlo-go 
  janus-idp.io/tekton: mtc7mndlo-go
  backstage.io/kubernetes-id: mtc7mndlo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mtc7mndlo-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml