apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mtc7mndlo-go-gitops
  description: This is GitOps manifest for mtc7mndlo-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=mtc7mndlo-go
    backstage.io/kubernetes-id: mtc7mndlo-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/mtc7mndlo-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mtc7mndlo-go
