apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mtc7mndlo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mtc7mndlo-go 
  name: mtc7mndlo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mtc7mndlo-go 
